### ISSUE TITLE
How can we test this? 

### ISSUE THREAD

**Issue by mwarger** [nrwl/nx-expo#1]
I'd like to help test this plug-in. I tried installing as a dependency from the GitHub repo itself, but I haven't had any luck in using it as it says it doesn't expose any generators. Any advice for testing this locally?  Or are there any plans to publish this as a package for pre-release testing? Thank you.

**Comment by StalkAltan** [comment]
Hi @mwarger  !

This package is currently under development and isn't at a point where it's ready for general consumption. If you're really interested in trying it out, you can do so by pulling this repo and building the package yourself through Nx, then installing from that local copy.

Since the package is still in Alpha, I would probably just keep an eye on this repo as the team gets ready for beta and stable releases.

Thanks for the interest!
