### ISSUE TITLE
How do we use this lol, can't seem to install this via the cli?!

### ISSUE THREAD

**Issue by algoflows** [nrwl/nx-expo#2]
Any guidance on using this would be greatly appreciated, I can't seem to install this via the cli using Yarn or NPM...

What's the step by step proceedure for a junior developer here new to expo and nx?

Many thanks :)

**Comment by algoflows** [comment]
Anyone maintaining this?

**Comment by StalkAltan** [comment]
Hi @JuniorDEVed ! Thanks for the interest.

This package is currently under development and isn't at a point where it's ready for general consumption. If you're *really* interested in trying it out, you can do so by pulling this repo and building the package yourself through Nx, then installing from that local copy.

Since the package is still in Alpha, I wouldn't really recommend that if you're new to both Nx and Expo, but keep an eye on the main `nrwl/nx` repo for when this gets released officially!

**Comment by algoflows** [comment]
Is there some way of using expo without using the plugins installation process? Also are there any good tutorials or resources on how to create our own plugins? I would love to use Remix instead of Nextjs but we can only use official plugins unless we build our own. Am I correct?

**Comment by algoflows** [comment]
> Hi @JuniorDEVed ! Thanks for the interest.
> 
> This package is currently under development and isn't at a point where it's ready for general consumption. If you're _really_ interested in trying it out, you can do so by pulling this repo and building the package yourself through Nx, then installing from that local copy.
> 
> Since the package is still in Alpha, I wouldn't really recommend that if you're new to both Nx and Expo, but keep an eye on the main `nrwl/nx` repo for when this gets released officially!

Is there any time estimations on when this might happen, when will the expo plugin be fully released?

**Comment by algoflows** [comment]
24 days ago no one answered and closed the thread without addressing further questions on expected release?! I see many more people starting to ask similar questions.
